# Generated by Django 3.2.4 on 2023-10-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_preguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('pregunta1', models.CharField(max_length=100)),
                ('Pregunta2', models.CharField(max_length=100)),
                ('Pregunta3', models.CharField(max_length=100)),
                ('Pregunta4', models.CharField(max_length=100)),
                ('Pregunta5', models.CharField(max_length=100)),
                ('Pregunta6', models.CharField(max_length=100)),
                ('Pregunta7', models.CharField(max_length=100)),
                ('Pregunta8', models.CharField(max_length=100)),
                ('Pregunta9', models.CharField(max_length=100)),
                ('Pregunta10', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='preguntas',
        ),
    ]
